/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'root' at '21/06/16 09:47' with Gradle 2.9
 *
 * @author root, @date 21/06/16 09:47
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
